### ISSUE TITLE
flexvolume swarm support?

### ISSUE THREAD

**Issue by pwFoo** [LINBIT/linstor-flexvolume#1]
Hi @rck ,

thanks for your quick response (https://github.com/LINBIT/drbdmanage-docker-volume/issues/3) and information about drbdmanage-docker-plugin and linstor.

> Linstor flexvolume plugin for Kubernetes

So linstor (flexvolume) is kubernetes only? I searching for a docker swarm solution.

**Comment by deleteriousEffect** [comment]
Yes, flexvolume is particular to kubernetes and couldn't be directly used with docker swarm iirc. As far as I know there is no commercial interest for us with docker swarm, so it's unfortunately not really something I could look into. If you were to talk to sales_us@linbit.com, you might could work with them.
